import { Theme } from "../theme.slint";

export component Toast inherits Rectangle {
    in property <string> message;
    in property <bool> show: false;

    width: 100%;
    height: 100%;

    if show: Rectangle {
        x: (parent.width - self.width) / 2;
        y: parent.height - self.height - 70px;
        width: bubble-layout.min-width;
        height: bubble-layout.min-height;
        border-radius: 8px;
        background: Theme.text;

        bubble-layout := HorizontalLayout {
            padding-left: 22px;
            padding-right: 22px;
            padding-top: 11px;
            padding-bottom: 11px;

            Text {
                text: root.message;
                color: Theme.bg;
                font-size: 14px;
                font-weight: 600;
            }
        }
    }
}
